import type { Metadata } from "next";
import "./layout.css"
import dotenv from 'dotenv';
dotenv.config();
console.log("page is loaded")

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
